apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-strategy
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: nginx-deployment-strategy
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-deployment-strategy
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate