apiVersion: batch/v1
kind: Job
metadata:
  name:  my-job
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 120
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name:  busybox
        image:  busybox
      restartPolicy: Never