apiVersion: batch/v1
kind: Job
metadata:
  name:  my-job-with-ttl
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name:  busybox
        image:  busybox
      restartPolicy: OnFailure