apiVersion: v1
kind: Service
metadata:
  name: portainer-service
spec:
  selector:
    app: portainer
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 9443
      targetPort: 9443
  type: LoadBalancer
