apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: minikube-argo-cicd
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchLabels:
      #           app: nginx
      #       topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: nginx:1.14.0
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "1Ki"
        imagePullPolicy: Always
        # readinessProbe:
        #     initialDelaySeconds: 30
        #     periodSeconds: 20
        #     httpGet:
        #       port: 80
        #       path: "/"
        # livenessProbe:
        #     initialDelaySeconds: 60
        #     periodSeconds: 20
        #     httpGet:
        #       port: 80
        #       path: "/"
        ports:
          - containerPort: 80
