# Loading each key value form a config map
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: minikube-argo-cicd
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.0
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: user
          imagePullPolicy: Always
          ports:
            - containerPort: 80
